# This is a basic workflow to help you get started with Actions

name: fetch-data

# Controls when the action will run. 
on:
  schedule:
    - cron: "02 4 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Fetch data from 2 days ago
        run: |
          export DATE=`date --date="2 days ago" +%Y-%m-%d`
          python3 src/rainfall.py -s stations.txt -d $DATE

      # Runs a set of commands using the runners shell
      - name: Commit new data
        run: |
          export DATE=`date --date="2 days ago" +%Y-%m-%d`
          # better email address: https://github.community/t/github-actions-bot-email-address/17204/7
          git config --global user.name 'github-actions[bot]'
          # userid from https://api.github.com/users/jamesp
          git config --global user.email '22805+github-actions[bot]@users.noreply.github.com'
          git add data
          if [ -z "$(git status --porcelain)" ]; then 
            # Working directory clean
            echo "Nothing to commit"
          else 
            git commit -m "Data added for ${DATE}"
            git push
          fi
          
      - name: Push to tinybird
        run: |
          python3 scripts/single_file.py output.csv
          curl \
            -H 'Authorization: Bearer ${{ secrets.TINYBIRD_KEY }}' \
            -X POST 'https://api.tinybird.co/v0/datasources?format=csv&name=daily_rainfall&mode=replace' \
            -F "csv=@output.csv"
